# .pre-commit-config.yaml

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Python
      - id: check-ast
      - id: debug-statements
      - id: requirements-txt-fixer
      # Other languages
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: sort-simple-yaml
      # Whitespace
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      # file names
      - id: check-case-conflict
      # - id: check-illegal-windows-names
      - id: name-tests-test
        args: ["--pytest-test-first"]
      # bad file content
      - id: check-merge-conflict
      - id: check-added-large-files
      # executables
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      # symlinks
      - id: check-symlinks
      - id: destroyed-symlinks

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.4
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1  # Use the latest version or a specific tag
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --remove-unused-variables, --expand-star-imports, --ignore-init-module-imports]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8  # Use the latest version or a specific tag
    hooks:
      - id: prettier
        files: \.json$
        args: ["--parser", "json"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0  # Use the latest version or a specific tag
    hooks:
      - id: mypy
